import json

file_path = "tests/SemanticKITTI/HGP_SemanticKITTI_4D_Panoptic.ipynb"
with open(file_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell["cell_type"] == "code" and cell["source"] and "4.1 HGP Clustering" in cell["source"][0]:
        new_source = [
            "# @title 4.1 HGP Clustering\n",
            "import time\n",
            "import numpy as np\n",
            "import os\n",
            "\n",
            "# --- Import sécurisé de HGPClusterer ---\n",
            "try:\n",
            "    from hgp_clusterer import HGPClusterer\n",
            "except ImportError:\n",
            "    print(\"⚠️ Module HGPClusterer introuvable. Tentative de correction du path...\")\n",
            "    import sys\n",
            "    if \"/content/HGP-clusterer/src\" not in sys.path:\n",
            "        sys.path.append(\"/content/HGP-clusterer/src\")\n",
            "    try:\n",
            "        from hgp_clusterer import HGPClusterer\n",
            "        print(\"✅ HGPClusterer importé avec succès après correction du path.\")\n",
            "    except ImportError as e:\n",
            "        raise RuntimeError(f\"❌ Impossible d'importer HGPClusterer même après correction. Erreur: {e}. Veuillez vérifier la compilation en section 1.5.\")\n",
            "\n",
            "K = 3 # @param {type:\"integer\"}\n",
            "MIN_CLUSTER_SIZE = 1 # @param {type:\"integer\"}\n",
            "EXP_Z = 1 # @param {type:\"number\"}\n",
            "\n",
            "CURRENT_GT_INSTANCES = None\n",
            "\n",
            "def oracle_Gini(parent_pts_idx, children_pts_idx_list, ε_Gini=0.001):\n",
            "    \"\"\"\n",
            "    Splitting basé sur l'index de Gini (Oracle).\n",
            "    Utilise CURRENT_GT_INSTANCES qui doit être mis à jour avant le fit.\n",
            "    \"\"\"\n",
            "    global CURRENT_GT_INSTANCES\n",
            "    if CURRENT_GT_INSTANCES is None or len(parent_pts_idx) == 0: return False\n",
            "    \n",
            "    def get_gini(indices):\n",
            "        if len(indices) == 0: return 0.0\n",
            "        labels = CURRENT_GT_INSTANCES[indices] # Utilisation des labels locaux à la classe\n",
            "        if len(labels) == 0: return 0.0\n",
            "        _, counts = np.unique(labels, return_counts=True)\n",
            "        probs = counts / len(labels)\n",
            "        return 1.0 - np.sum(probs**2)\n",
            "    \n",
            "    gini_p = get_gini(parent_pts_idx)\n",
            "    if gini_p < ε_Gini: return False # Déjà très pur\n",
            "    \n",
            "    n_total = len(parent_pts_idx)\n",
            "    gini_c_weighted = 0.0\n",
            "    for c_pts in children_pts_idx_list:\n",
            "        if len(c_pts) == 0: continue\n",
            "        gini_c_weighted += (len(c_pts) / n_total) * get_gini(c_pts)\n",
            "    \n",
            "    # On split si l'impureté diminue de façon notable\n",
            "    return gini_c_weighted < (gini_p - ε_Gini)\n",
            "\n",
            "SPLITTING_REGISTRY = {\n",
            "    \"None\": None,\n",
            "    \"oracle_Gini\": oracle_Gini\n",
            "}\n",
            "\n",
            "# @geogram_install/include/geogram1/geogram/parameterization/mesh_global_param.h\n",
            "SPLITTING_MODE = \"oracle_Gini\" # @param [\"None\", \"oracle_Gini\"] {allow-input: true}\n",
            "DBSCAN_FACTOR = 2.0 # @param {type:\"number\"}\n",
            "DT_FRAME = DBSCAN_FACTOR * DT_SCALE\n",
            "\n",
            "# Vérification préalable des données\n",
            "if X_clustering is None or len(X_clustering) == 0:\n",
            "    raise RuntimeError(\"Erreur critique: X_clustering est vide ou n'est pas défini. Veuillez vérifier la cellule 'Construction du Nuage 4D'.\")\n",
            "\n",
            "# Initialisation du tableau global des prédictions (ID des instances)\n",
            "# -1 indique le bruit/non-assigné\n",
            "labels_pred = np.full(len(X_clustering), -1, dtype=int)\n",
            "global_instance_offset = 0\n",
            "\n",
            "# --- Boucle par classe sémantique ---\n",
            "# Pour une segmentation panoptique propre, le clustering est indépendant pour chaque classe \"Thing\".\n",
            "\n",
            "unique_classes = np.unique(Y_sem)\n",
            "print(f\"Classes sémantiques trouvées dans ce bloc de frames : {unique_classes}\")\n",
            "\n",
            "for semantic_class in unique_classes:\n",
            "    if semantic_class not in THINGS_CLASSES and SEMANTIC_MODE == \"Oracle\":\n",
            "        # Ce cas ne devrait pas arriver si le nuage a été pré-filtré, mais par sécurité :\n",
            "        continue\n",
            "    \n",
            "    # Masque pour extraire uniquement les points de la classe courante\n",
            "    class_mask = (Y_sem == semantic_class)\n",
            "    X_class = X_clustering[class_mask]\n",
            "    Y_inst_class = Y_inst[class_mask]\n",
            "    CURRENT_GT_INSTANCES = Y_inst_class # Mise à jour pour oracle_Gini\n",
            "\n",
            "    if len(X_class) < MIN_CLUSTER_SIZE:\n",
            "        # Pas assez de points pour former un cluster, on les laisse à -1\n",
            "        print(f\"Classe {semantic_class} ignorée (seulement {len(X_class)} points, min={MIN_CLUSTER_SIZE}).\")\n",
            "        continue\n",
            "\n",
            "    print(f\"--- Traitement de la classe sémantique {semantic_class} ({len(X_class)} points) ---\")\n",
            "\n",
            "    clusterer = HGPClusterer(\n",
            "        K=K, min_cluster_size=MIN_CLUSTER_SIZE, min_samples=K+1,\n",
            "        splitting=SPLITTING_REGISTRY.get(SPLITTING_MODE),\n",
            "        expZ=EXP_Z,\n",
            "        method=DT_FRAME,\n",
            "        backend=BACKEND,\n",
            "        cgal_root=os.environ.get(\"CGALDELAUNAY_ROOT\"),\n",
            "        verbose=False # Rendu silencieux pour ne pas spammer la boucle\n",
            "    )\n",
            "\n",
            "    t0 = time.time()\n",
            "    try:\n",
            "        class_labels_pred = clusterer.fit_predict(X_class)\n",
            "        num_clusters = len(set(class_labels_pred)) - (1 if -1 in class_labels_pred else 0)\n",
            "        print(f\"  -> {num_clusters} clusters trouvés en {time.time()-t0:.2f}s.\")\n",
            "        \n",
            "        # On assigne des IDs globaux uniques à ces nouveaux clusters\n",
            "        valid_cluster_mask = class_labels_pred >= 0\n",
            "        if np.any(valid_cluster_mask):\n",
            "            # Décalage des labels pour qu'ils soient uniques sur toute la scène\n",
            "            class_labels_pred[valid_cluster_mask] += global_instance_offset\n",
            "            \n",
            "            # Injection dans le tableau global\n",
            "            labels_pred[class_mask] = class_labels_pred\n",
            "            \n",
            "            # Mise à jour de l'offset pour la prochaine classe\n",
            "            global_instance_offset = np.max(class_labels_pred) + 1\n",
            "            \n",
            "    except Exception as e:\n",
            "        print(f\"  -> Erreur durant le clustering de la classe {semantic_class}: {e}\")\n",
            "\n",
            "print(f\"\\nClustering global terminé. Total instances uniques détectées : {global_instance_offset}\")\n"
        ]
        cell["source"] = new_source

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)

print("Notebook clustering cell cleaned up.")
