import json
import os

with open('tests/SemanticKITTI/HGP_SemanticKITTI_4D_Panoptic.ipynb', 'r') as f:
    nb = json.load(f)

# Modify markdown cell 0
nb['cells'][0]['source'] = [
    "# HGP-clusterer : 3D puis 4D Panoptic Segmentation sur SemanticKITTI\n",
    "\n",
    "Ce notebook implémente un pipeline de segmentation panoptique en \"streaming\" en utilisant **HGP-clusterer**.\n",
    "\n",
    "**Pipeline :**\n",
    "1.  **Setup** : Installation des dépendances.\n",
    "2.  **Data** : Chargement d'une séquence SemanticKITTI.\n",
    "3.  **Preprocessing** : Construction des nuages de points.\n",
    "4.  **Clustering & Tracking (Streaming)** : \n",
    "    - Initialisation (Frame 0) : Segmentation d'instance 3D (ou BEV) et création des représentations des clusters (volume, classe, vitesse).\n",
    "    - Suivi (Frames suivantes) : *En cours (itération frame par frame)*.\n",
    "5.  **Evaluation** : *Adaptée pour le suivi*.\n",
    "6.  **Visualisation** : Rendu interactif."
]

# Modify clustering cell 4.1 (which should be index 8 based on previous print)
# Let's find the cell with title 4.1 HGP Clustering
for i, cell in enumerate(nb['cells']):
    if len(cell['source']) > 0 and '4.1 HGP Clustering' in cell['source'][0]:
        nb['cells'][i]['source'] = [
            "# @title 4.1 HGP Clustering (Streaming Frame 0)\n",
            "import time\n",
            "import numpy as np\n",
            "import os\n",
            "\n",
            "# --- Import sécurisé de HGPClusterer ---\n",
            "try:\n",
            "    from hgp_clusterer import HGPClusterer\n",
            "except ImportError:\n",
            "    print(\"⚠️ Module HGPClusterer introuvable. Tentative de correction du path...\")\n",
            "    import sys\n",
            "    if \"/content/HGP-clusterer/src\" not in sys.path:\n",
            "        sys.path.append(\"/content/HGP-clusterer/src\")\n",
            "    try:\n",
            "        from hgp_clusterer import HGPClusterer\n",
            "        print(\"✅ HGPClusterer importé avec succès après correction du path.\")\n",
            "    except ImportError as e:\n",
            "        raise RuntimeError(f\"❌ Impossible d'importer HGPClusterer même après correction. Erreur: {e}. Veuillez vérifier la compilation en section 1.5.\")\n",
            "\n",
            "K = 3 # @param {type:\"integer\"}\n",
            "MIN_CLUSTER_SIZE = 1 # @param {type:\"integer\"}\n",
            "EXP_Z = 1 # @param {type:\"number\"}\n",
            "\n",
            "CURRENT_GT_INSTANCES = None\n",
            "\n",
            "def oracle_Gini(parent_pts_idx, children_pts_idx_list, ε_Gini=0.001):\n",
            "    \"\"\"\n",
            "    Splitting basé sur l'index de Gini (Oracle).\n",
            "    Utilise CURRENT_GT_INSTANCES qui doit être mis à jour avant le fit.\n",
            "    \"\"\"\n",
            "    global CURRENT_GT_INSTANCES\n",
            "    if CURRENT_GT_INSTANCES is None or len(parent_pts_idx) == 0: return False\n",
            "    \n",
            "    def get_gini(indices):\n",
            "        if len(indices) == 0: return 0.0\n",
            "        labels = CURRENT_GT_INSTANCES[indices]\n",
            "        if len(labels) == 0: return 0.0\n",
            "        _, counts = np.unique(labels, return_counts=True)\n",
            "        probs = counts / len(labels)\n",
            "        return 1.0 - np.sum(probs**2)\n",
            "    \n",
            "    gini_p = get_gini(parent_pts_idx)\n",
            "    if gini_p < ε_Gini: return False\n",
            "    \n",
            "    n_total = len(parent_pts_idx)\n",
            "    gini_c_weighted = 0.0\n",
            "    for c_pts in children_pts_idx_list:\n",
            "        if len(c_pts) == 0: continue\n",
            "        gini_c_weighted += (len(c_pts) / n_total) * get_gini(c_pts)\n",
            "    \n",
            "    return gini_c_weighted < (gini_p - ε_Gini)\n",
            "\n",
            "SPLITTING_REGISTRY = {\n",
            "    \"None\": None,\n",
            "    \"oracle_Gini\": oracle_Gini\n",
            "}\n",
            "\n",
            "SPLITTING_MODE = \"oracle_Gini\" # @param [\"None\", \"oracle_Gini\"] {allow-input: true}\n",
            "DBSCAN_FACTOR = 2.0 # @param {type:\"number\"}\n",
            "DT_FRAME = DBSCAN_FACTOR * DT_SCALE\n",
            "\n",
            "# Vérification préalable des données\n",
            "if X_clustering is None or len(X_clustering) == 0:\n",
            "    raise RuntimeError(\"Erreur critique: X_clustering est vide ou n'est pas défini. Veuillez vérifier la cellule 'Construction du Nuage 4D'.\")\n",
            "\n",
            "# Initialisation du tableau global des prédictions (ID des instances)\n",
            "labels_pred = np.full(len(X_clustering), -1, dtype=int)\n",
            "global_instance_offset = 0\n",
            "\n",
            "frames = np.unique(Time_idx)\n",
            "print(f\"Frames à traiter en streaming : {frames}\")\n",
            "\n",
            "# Stockage des informations sur les clusters\n",
            "clusters_info = {}\n",
            "\n",
            "for t in frames:\n",
            "    print(f\"\\n=== Traitement de la frame {t} ===\")\n",
            "    frame_mask = (Time_idx == t)\n",
            "    X_frame = X_clustering[frame_mask]\n",
            "    Y_sem_frame = Y_sem[frame_mask]\n",
            "    Y_inst_frame = Y_inst[frame_mask]\n",
            "    \n",
            "    # Indices globaux pour mettre à jour labels_pred\n",
            "    global_indices = np.where(frame_mask)[0]\n",
            "    \n",
            "    if t == 0:\n",
            "        # Première frame : on lance HGP-Clusterer\n",
            "        unique_classes = np.unique(Y_sem_frame)\n",
            "        print(f\"Classes sémantiques trouvées dans la frame 0 : {unique_classes}\")\n",
            "        \n",
            "        for semantic_class in unique_classes:\n",
            "            if semantic_class not in THINGS_CLASSES and SEMANTIC_MODE == \"Oracle\":\n",
            "                continue\n",
            "            \n",
            "            class_mask = (Y_sem_frame == semantic_class)\n",
            "            X_class = X_frame[class_mask]\n",
            "            Y_inst_class = Y_inst_frame[class_mask]\n",
            "            class_global_indices = global_indices[class_mask]\n",
            "            CURRENT_GT_INSTANCES = Y_inst_class\n",
            "            \n",
            "            if len(X_class) < MIN_CLUSTER_SIZE:\n",
            "                continue\n",
            "                \n",
            "            print(f\"--- Traitement de la classe sémantique {semantic_class} ({len(X_class)} points) ---\")\n",
            "            \n",
            "            clusterer = HGPClusterer(\n",
            "                K=K, min_cluster_size=MIN_CLUSTER_SIZE, min_samples=K+1,\n",
            "                splitting=SPLITTING_REGISTRY.get(SPLITTING_MODE),\n",
            "                expZ=EXP_Z,\n",
            "                method=DT_FRAME, # On garde DT_FRAME bien qu'on soit sur une seule frame pour l'instant\n",
            "                backend=BACKEND,\n",
            "                cgal_root=os.environ.get(\"CGALDELAUNAY_ROOT\"),\n",
            "                verbose=False\n",
            "            )\n",
            "            \n",
            "            t0 = time.time()\n",
            "            try:\n",
            "                class_labels_pred = clusterer.fit_predict(X_class)\n",
            "                num_clusters = len(set(class_labels_pred)) - (1 if -1 in class_labels_pred else 0)\n",
            "                print(f\"  -> {num_clusters} clusters trouvés en {time.time()-t0:.2f}s.\")\n",
            "                \n",
            "                valid_cluster_mask = class_labels_pred >= 0\n",
            "                if np.any(valid_cluster_mask):\n",
            "                    class_labels_pred[valid_cluster_mask] += global_instance_offset\n",
            "                    labels_pred[class_global_indices] = class_labels_pred\n",
            "                    \n",
            "                    # --- Représentation des clusters (Volume, Classe, Vitesse) ---\n",
            "                    unique_clusters_class = np.unique(class_labels_pred[valid_cluster_mask])\n",
            "                    for cid in unique_clusters_class:\n",
            "                        # On récupère les points 3D originaux pour calculer le volume\n",
            "                        pts_3d = X_4d[class_global_indices][class_labels_pred == cid][:, :3]\n",
            "                        dims = np.max(pts_3d, axis=0) - np.min(pts_3d, axis=0)\n",
            "                        volume = np.prod(dims)\n",
            "                        \n",
            "                        # Vitesse (inconnue sur la frame 0)\n",
            "                        vitesse = [0.0, 0.0, 0.0]\n",
            "                        \n",
            "                        clusters_info[cid] = {\n",
            "                            \"classe\": semantic_class,\n",
            "                            \"volume\": volume,\n",
            "                            \"vitesse\": vitesse,\n",
            "                            \"num_points\": len(pts_3d)\n",
            "                        }\n",
            "                        \n",
            "                    global_instance_offset = np.max(class_labels_pred) + 1\n",
            "            except Exception as e:\n",
            "                print(f\"  -> Erreur durant le clustering de la classe {semantic_class}: {e}\")\n",
            "                \n",
            "        print(\"\\nRésumé des clusters de la frame 0 :\")\n",
            "        for cid, info in clusters_info.items():\n",
            "            print(f\"  Cluster {cid:03d} | Classe: {info['classe']} | Volume: {info['volume']:.2f} m³ | Vitesse (init): {info['vitesse']} | Points: {info['num_points']}\")\n",
            "\n",
            "    else:\n",
            "        # Pour les frames suivantes, pour l'instant on ne fait rien (on prépare juste le streaming)\n",
            "        # TODO: Implémenter le suivi (tracking/association)\n",
            "        pass\n",
            "\n",
            "print(f\"\\nStreaming initial terminé. Total instances uniques détectées : {global_instance_offset}\\n\")\n"
        ]

with open('tests/SemanticKITTI/HGP-Clusterer_SemanticKITTI_3D_then_4D_Panoptic.ipynb', 'w') as f:
    json.dump(nb, f, indent=2)

